### ISSUE TITLE
Feature Request: Use css style to make task more visually appealing

### ISSUE THREAD

**Issue by krillin666** [ahonn/logseq-plugin-todo#7]
Substitute the priorities of tasks from letter based to icon based like in the *Oxford Blue* theme, like:

```css
.priority {
  font-size: 0;
  visibility: hidden;
}

a[priority]::before,
.priority::before {
  background-repeat: no-repeat;
  border: 1px solid var(--transparent);
  border-radius: 100%;
  display: inline-block;
  font-size: 12px;
  height: 16px;
  visibility: visible;
  width: 16px;
}

a[priority]::before {
  /* display: inline-flex ; */
  margin-right: 5px;
  /* margin-top: 5px; */
}

a.tooltip-priority {
  transition: none;
}

a[priority="A"]::before,
.priority[href="#/page/A"]::before {
  background-color: var(--red);
  content: " ";
}
a[priority="B"]::before,
.priority[href="#/page/B"]::before {
  background-color: var(--orange);
  content: " ";
}
a[priority="C"]::before,
.priority[href="#/page/C"]::before {
  background-color: var(--green);
  content: " ";
}
```
Or like this (made for Obsidian): [https://github.com/mishacreatrix/obsidian-todoist-plugin-styles/blob/main/obsidianStyles.css](https://github.com/mishacreatrix/obsidian-todoist-plugin-styles/blob/main/obsidianStyles.css)
